"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Zone = { id: number; name: string; zone_type: string; record_count: number; comment: string };
type RecordItem = { id: number; name: string; type: string; value: string; ttl: number; routing_policy: string };
type Dashboard = { counts: Record<string, number>; api_status: string; database: string };
type TrafficPolicy = { id: number; name: string; policy_type: string; status: string };
type HealthCheck = { id: number; name: string; endpoint: string; check_type: string; status: string };
type ResolverEndpoint = { id: number; name: string; direction: string; status: string };
type Profile = { id: number; name: string; description: string; status: string };
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";
const recordTypes = ["A", "AAAA", "CNAME", "TXT", "MX", "NS", "PTR", "SRV", "CAA"];

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`${API}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options?.headers || {}) } });
  if (!response.ok) throw new Error((await response.json()).detail || "Request failed");
  return response.json();
}

export default function Home() {
  const [authenticated, setAuthenticated] = useState(false);
  const [zones, setZones] = useState<Zone[]>([]);
  const [selectedZone, setSelectedZone] = useState<Zone | null>(null);
  const [records, setRecords] = useState<RecordItem[]>([]);
  const [zoneSearch, setZoneSearch] = useState("");
  const [recordSearch, setRecordSearch] = useState("");
  const [recordFilter, setRecordFilter] = useState("");
  const [modal, setModal] = useState<"zone" | "record" | "traffic-policy" | "health-check" | "resolver-endpoint" | "profile" | null>(null);
  const [editing, setEditing] = useState<Zone | RecordItem | null>(null);
  const [notice, setNotice] = useState("");
  const [activeNav, setActiveNav] = useState("Hosted zones");
  const [page, setPage] = useState(1);
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [trafficPolicies, setTrafficPolicies] = useState<TrafficPolicy[]>([]);
  const [healthChecks, setHealthChecks] = useState<HealthCheck[]>([]);
  const [resolverEndpoints, setResolverEndpoints] = useState<ResolverEndpoint[]>([]);
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const perPage = 8;
  useEffect(() => { setAuthenticated(window.localStorage.getItem("route53-session") === "active"); }, []);

  const loadZones = async () => setZones(await request<Zone[]>(`/zones?search=${encodeURIComponent(zoneSearch)}`));
  const loadRecords = async () => selectedZone && setRecords(await request<RecordItem[]>(`/zones/${selectedZone.id}/records?search=${encodeURIComponent(recordSearch)}&record_type=${recordFilter}`));
  const loadTrafficPolicies = async () => setTrafficPolicies(await request<TrafficPolicy[]>("/traffic-policies"));
  const loadHealthChecks = async () => setHealthChecks(await request<HealthCheck[]>("/health-checks"));
  const loadResolverEndpoints = async () => setResolverEndpoints(await request<ResolverEndpoint[]>("/resolver/endpoints"));
  const loadProfiles = async () => setProfiles(await request<Profile[]>("/profiles"));
  useEffect(() => { loadZones().catch(() => setNotice("Backend unavailable. Start FastAPI to load your zones.")); }, [zoneSearch]);
  useEffect(() => { loadRecords().catch(() => setNotice("Could not load records.")); }, [selectedZone, recordSearch, recordFilter]);
  useEffect(() => {
    if (activeNav === "Hosted zones") return;
    const paths: Record<string, string> = { Dashboard: "/dashboard", "Traffic policies": "/traffic-policies", "Health checks": "/health-checks", Resolver: "/resolver/endpoints", Profiles: "/profiles" };
    request<any>(paths[activeNav]).then(data => {
      if (activeNav === "Dashboard") setDashboard(data);
      if (activeNav === "Traffic policies") setTrafficPolicies(data);
      if (activeNav === "Health checks") setHealthChecks(data);
      if (activeNav === "Resolver") setResolverEndpoints(data);
      if (activeNav === "Profiles") setProfiles(data);
    }).catch(() => setNotice(`Could not load ${activeNav.toLowerCase()}.`));
  }, [activeNav]);
  const visibleZones = useMemo(() => zones.slice((page - 1) * perPage, page * perPage), [zones, page]);

  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 3500); };
  const signOut = () => { window.localStorage.removeItem("route53-session"); setAuthenticated(false); };
  if (!authenticated) return <Login onLogin={() => { window.localStorage.setItem("route53-session", "active"); setAuthenticated(true); }} />;
  const removeZone = async (zone: Zone) => { if (!window.confirm(`Delete hosted zone ${zone.name}?`)) return; await request(`/zones/${zone.id}`, { method: "DELETE" }); setSelectedZone(null); await loadZones(); notify("Hosted zone deleted"); };
  const removeRecord = async (record: RecordItem) => { if (!selectedZone || !window.confirm(`Delete ${record.type} record?`)) return; await request(`/zones/${selectedZone.id}/records/${record.id}`, { method: "DELETE" }); await loadRecords(); notify("Record deleted"); };

  return <div className="shell">
    <header className="topbar"><div className="brand"><span className="aws">aws</span><span className="brand-divider" /> <span>Management Console</span></div><div className="top-actions"><button className="header-icon" aria-label="Search" title="Search"><span className="icon icon-search" /></button><button className="region-button">Region: Global <span className="icon icon-chevron" /></button><button className="header-icon" aria-label="Open navigation menu" title="Menu"><span className="icon icon-menu" /></button><span className="avatar">D</span><button className="top-link" onClick={signOut}>Sign out</button></div></header>
    <div className="workspace">
      <aside className="sidebar"><div className="service-title"><span className="route-icon" aria-hidden="true"><span className="route-mark" /></span><span>Route 53</span></div><div className="nav-label">ROUTE 53</div>{["Dashboard", "Hosted zones", "Traffic policies", "Health checks", "Resolver", "Profiles"].map(item => <button className={`nav-item ${activeNav === item ? "active" : ""}`} onClick={() => setActiveNav(item)} key={item}><span className={`nav-icon nav-icon-${item.toLowerCase().replace(" ", "-")}`} aria-hidden="true" />{item}{item !== "Hosted zones" && <small aria-hidden="true"><span className="icon icon-chevron-right" /></small>}</button>)}<div className="sidebar-bottom"><button className="nav-item"><span className="nav-icon nav-icon-help" aria-hidden="true" />Help</button><button className="nav-item"><span className="nav-icon nav-icon-settings" aria-hidden="true" />Settings</button></div></aside>
      <main className="main">{activeNav !== "Hosted zones" ? <FeatureView activeNav={activeNav} dashboard={dashboard} trafficPolicies={trafficPolicies} healthChecks={healthChecks} resolverEndpoints={resolverEndpoints} profiles={profiles} onCreateTrafficPolicy={() => setModal("traffic-policy")} onCreateHealthCheck={() => setModal("health-check")} onCreateResolverEndpoint={() => setModal("resolver-endpoint")} onCreateProfile={() => setModal("profile")} /> : <>
        <div className="breadcrumbs">Route 53 <span>›</span> Hosted zones</div>
        <div className="heading-row"><div><h1>Hosted zones</h1><p>Manage the hosted zones for your domains.</p></div><button className="primary" onClick={() => { setEditing(null); setModal("zone"); }}>Create hosted zone</button></div>
        {notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}
        <section className="panel"><div className="panel-heading"><div><h2>Hosted zones <span className="count">{zones.length}</span></h2><p>Hosted zones contain the records that define how you want to route traffic for a domain.</p></div><div className="panel-tools"><button className="icon-button" title="Refresh" aria-label="Refresh hosted zones" onClick={() => loadZones()}><span className="icon icon-refresh" /></button><button className="icon-button" title="Preferences" aria-label="Table preferences"><span className="icon icon-table" /></button></div></div><div className="toolbar"><label className="search"><span className="icon icon-search" aria-hidden="true" /><input placeholder="Find hosted zones" value={zoneSearch} onChange={e => { setZoneSearch(e.target.value); setPage(1); }} /></label><button className="filter">Filter <span className="icon icon-chevron" /></button></div><table><thead><tr><th>Hosted zone name</th><th>Type</th><th>Record count</th><th>Comment</th><th>Actions</th></tr></thead><tbody>{visibleZones.map(zone => <tr key={zone.id} className={selectedZone?.id === zone.id ? "selected" : ""}><td><button className="link" onClick={() => setSelectedZone(zone)}>{zone.name}</button></td><td>{zone.zone_type}</td><td>{zone.record_count}</td><td>{zone.comment || "-"}</td><td className="row-actions"><button onClick={() => { setEditing(zone); setModal("zone"); }}>Edit</button><button onClick={() => removeZone(zone)}>Delete</button></td></tr>)}</tbody></table><TableFooter page={page} total={zones.length} perPage={perPage} setPage={setPage} /></section>
        {selectedZone && <section className="panel records-panel"><div className="panel-heading"><div><div className="sub-breadcrumb">Hosted zones / <strong>{selectedZone.name}</strong></div><h2>Records <span className="count">{records.length}</span></h2><p>Records define how traffic is routed for this hosted zone.</p></div><button className="primary" onClick={() => { setEditing(null); setModal("record"); }}>Create record</button></div><div className="toolbar"><label className="search"><span className="icon icon-search" aria-hidden="true" /><input placeholder="Search records" value={recordSearch} onChange={e => setRecordSearch(e.target.value)} /></label><select value={recordFilter} onChange={e => setRecordFilter(e.target.value)}><option value="">All record types</option>{recordTypes.map(type => <option key={type}>{type}</option>)}</select><button className="filter">Filter <span className="icon icon-chevron" /></button></div><table><thead><tr><th>Name</th><th>Type</th><th>Value</th><th>TTL</th><th>Routing policy</th><th>Actions</th></tr></thead><tbody>{records.map(record => <tr key={record.id}><td>{record.name}</td><td><span className="type-pill">{record.type}</span></td><td className="value-cell">{record.value}</td><td>{record.ttl}</td><td>{record.routing_policy}</td><td className="row-actions"><button onClick={() => { setEditing(record); setModal("record"); }}>Edit</button><button onClick={() => removeRecord(record)}>Delete</button></td></tr>)}</tbody></table>{records.length === 0 && <div className="empty">No records match your search.</div>}</section>}
      </>}</main>
    </div>
    {modal === "zone" && <ZoneModal editing={editing as Zone | null} close={() => setModal(null)} save={async data => { if (editing) await request(`/zones/${(editing as Zone).id}`, { method: "PATCH", body: JSON.stringify(data) }); else await request("/zones", { method: "POST", body: JSON.stringify(data) }); setModal(null); await loadZones(); notify(editing ? "Hosted zone updated" : "Hosted zone created"); }} />}
    {modal === "record" && selectedZone && <RecordModal editing={editing as RecordItem | null} close={() => setModal(null)} save={async data => { const path = `/zones/${selectedZone.id}/records${editing ? `/${(editing as RecordItem).id}` : ""}`; await request(path, { method: editing ? "PATCH" : "POST", body: JSON.stringify(data) }); setModal(null); await loadRecords(); await loadZones(); notify(editing ? "Record updated" : "Record created"); }} />}
    {modal === "traffic-policy" && <TrafficPolicyModal close={() => setModal(null)} save={async data => { await request("/traffic-policies", { method: "POST", body: JSON.stringify(data) }); setModal(null); await loadTrafficPolicies(); notify("Traffic policy created"); }} />}
    {modal === "health-check" && <HealthCheckModal close={() => setModal(null)} save={async data => { await request("/health-checks", { method: "POST", body: JSON.stringify(data) }); setModal(null); await loadHealthChecks(); notify("Health check created"); }} />}
    {modal === "resolver-endpoint" && <ResolverEndpointModal close={() => setModal(null)} save={async data => { await request("/resolver/endpoints", { method: "POST", body: JSON.stringify(data) }); setModal(null); await loadResolverEndpoints(); notify("Resolver endpoint created"); }} />}
    {modal === "profile" && <ProfileModal close={() => setModal(null)} save={async data => { await request("/profiles", { method: "POST", body: JSON.stringify(data) }); setModal(null); await loadProfiles(); notify("Profile created"); }} />}
  </div>;
}

function TableFooter({ page, total, perPage, setPage }: { page: number; total: number; perPage: number; setPage: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / perPage)); return <div className="table-footer"><span>Showing {total ? (page - 1) * perPage + 1 : 0}–{Math.min(page * perPage, total)} of {total}</span><div><button disabled={page === 1} onClick={() => setPage(page - 1)}>‹</button><span>{page} / {pages}</span><button disabled={page === pages} onClick={() => setPage(page + 1)}>›</button></div></div>; }
function FeatureView({ activeNav, dashboard, trafficPolicies, healthChecks, resolverEndpoints, profiles, onCreateTrafficPolicy, onCreateHealthCheck, onCreateResolverEndpoint, onCreateProfile }: { activeNav: string; dashboard: Dashboard | null; trafficPolicies: TrafficPolicy[]; healthChecks: HealthCheck[]; resolverEndpoints: ResolverEndpoint[]; profiles: Profile[]; onCreateTrafficPolicy: () => void; onCreateHealthCheck: () => void; onCreateResolverEndpoint: () => void; onCreateProfile: () => void }) {
  if (activeNav === "Dashboard") return <DashboardView dashboard={dashboard} />;
  if (activeNav === "Traffic policies") return <ResourceTable title="Traffic policies" createLabel="traffic policy" onCreate={onCreateTrafficPolicy} description="Route traffic across endpoints using reusable routing policies." columns={["Name", "Policy type", "Status"]} rows={trafficPolicies.map(item => [item.name, item.policy_type, item.status])} />;
  if (activeNav === "Health checks") return <ResourceTable title="Health checks" createLabel="health check" onCreate={onCreateHealthCheck} description="Monitor endpoints and use health status when routing traffic." columns={["Name", "Endpoint", "Type", "Status"]} rows={healthChecks.map(item => [item.name, item.endpoint, item.check_type, item.status])} />;
  if (activeNav === "Resolver") return <ResourceTable title="Resolver" createLabel="endpoint" onCreate={onCreateResolverEndpoint} description="Manage DNS forwarding endpoints for your network." columns={["Name", "Direction", "Status"]} rows={resolverEndpoints.map(item => [item.name, item.direction, item.status])} />;
  return <ResourceTable title="Profiles" createLabel="profile" onCreate={onCreateProfile} description="Reusable collections of DNS settings for your environments." columns={["Name", "Description", "Status"]} rows={profiles.map(item => [item.name, item.description, item.status])} />;
}
function DashboardView({ dashboard }: { dashboard: Dashboard | null }) { const counts = dashboard?.counts || {}; return <><div className="breadcrumbs">Route 53 <span>›</span> Dashboard</div><div className="heading-row"><div><h1>Dashboard</h1><p>Operational overview for this local Route 53 environment.</p></div></div><div className="stats-grid">{[["Hosted zones", counts.hosted_zones], ["DNS records", counts.records], ["Traffic policies", counts.traffic_policies], ["Health checks", counts.health_checks], ["Resolver endpoints", counts.resolver_endpoints], ["Profiles", counts.profiles]].map(([label, value]) => <section className="stat-card" key={String(label)}><span>{label}</span><strong>{value ?? "-"}</strong></section>)}</div><section className="panel dashboard-status"><h2>Environment status</h2><p>API: <strong>{dashboard?.api_status || "Loading..."}</strong> <span>Database: <strong>{dashboard?.database || "Loading..."}</strong></span></p></section></>; }
function ResourceTable({ title, createLabel, onCreate, description, columns, rows }: { title: string; createLabel?: string; onCreate?: () => void; description: string; columns: string[]; rows: string[][] }) { const label = createLabel || (title === "Resolver" ? "endpoint" : title.slice(0, -1).toLowerCase()); return <><div className="breadcrumbs">Route 53 <span>›</span> {title}</div><div className="heading-row"><div><h1>{title}</h1><p>{description}</p></div><button className="primary" disabled={!onCreate} onClick={onCreate}>Create {label}</button></div><section className="panel"><div className="panel-heading"><div><h2>{title} <span className="count">{rows.length}</span></h2><p>Data is stored locally in the demo SQLite database.</p></div></div><table><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex} className={cellIndex === row.length - 1 ? "status-cell" : ""}>{cell}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <div className="empty">No resources found.</div>}</section></>; }
function Login({ onLogin }: { onLogin: () => void }) { const [email, setEmail] = useState("demo@route53.local"); return <div className="login-shell"><div className="login-card"><div className="login-brand"><span className="aws">aws</span><span>Management Console</span></div><h1>Sign in to Route 53</h1><p className="modal-intro">Use the included demo account to access this mocked AWS console.</p><label>Email address<input type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><button className="primary login-button" onClick={onLogin}>Sign in</button><p className="login-note">Demo account: demo@route53.local</p></div></div>; }
function Modal({ title, children, close, submit }: { title: string; children: React.ReactNode; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="backdrop"><form className="modal" onSubmit={submit}><div className="modal-header"><h2>{title}</h2><button type="button" onClick={close}>×</button></div><div className="modal-body">{children}</div><div className="modal-footer"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Save</button></div></form></div>; }
function ZoneModal({ editing, close, save }: { editing: Zone | null; close: () => void; save: (data: { name: string; comment: string }) => Promise<void> }) { const [name, setName] = useState(editing?.name.replace(/\.$/, "") || ""); const [comment, setComment] = useState(editing?.comment || ""); return <Modal title={editing ? "Edit hosted zone" : "Create hosted zone"} close={close} submit={e => { e.preventDefault(); save({ name, comment }); }}><p className="modal-intro">A hosted zone is a container for records that define how you route traffic for a domain.</p><label>Domain name<input required value={name} onChange={e => setName(e.target.value)} placeholder="example.com" /></label><label>Comment (optional)<textarea value={comment} onChange={e => setComment(e.target.value)} placeholder="Describe this hosted zone" /></label><label>Type<select><option>Public hosted zone</option><option>Private hosted zone</option></select></label></Modal>; }
function RecordModal({ editing, close, save }: { editing: RecordItem | null; close: () => void; save: (data: { name: string; type: string; value: string; ttl: number; routing_policy: string }) => Promise<void> }) { const [name, setName] = useState(editing?.name || ""); const [type, setType] = useState(editing?.type || "A"); const [value, setValue] = useState(editing?.value || ""); const [ttl, setTtl] = useState(String(editing?.ttl || 300)); return <Modal title={editing ? "Edit record" : "Create record"} close={close} submit={e => { e.preventDefault(); save({ name, type, value, ttl: Number(ttl), routing_policy: "Simple" }); }}><p className="modal-intro">Enter the values for this DNS record. This clone stores records locally in SQLite.</p><label>Record name<input required value={name} onChange={e => setName(e.target.value)} placeholder="www.example.com" /></label><div className="form-grid"><label>Record type<select value={type} onChange={e => setType(e.target.value)}>{recordTypes.map(item => <option key={item}>{item}</option>)}</select></label><label>TTL (seconds)<input required type="number" min="0" value={ttl} onChange={e => setTtl(e.target.value)} /></label></div><label>Value<textarea required value={value} onChange={e => setValue(e.target.value)} placeholder="Enter record value" /></label></Modal>; }
function TrafficPolicyModal({ close, save }: { close: () => void; save: (data: { name: string; policy_type: string }) => Promise<void> }) { const [name, setName] = useState(""); const [policyType, setPolicyType] = useState("Latency-based"); return <Modal title="Create traffic policy" close={close} submit={e => { e.preventDefault(); save({ name, policy_type: policyType }); }}><p className="modal-intro">Create a reusable policy for routing traffic across endpoints.</p><label>Policy name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Primary website routing" /></label><label>Policy type<select value={policyType} onChange={e => setPolicyType(e.target.value)}><option>Latency-based</option><option>Weighted</option><option>Geolocation</option><option>Failover</option></select></label></Modal>; }
function HealthCheckModal({ close, save }: { close: () => void; save: (data: { name: string; endpoint: string; check_type: string }) => Promise<void> }) { const [name, setName] = useState(""); const [endpoint, setEndpoint] = useState(""); const [checkType, setCheckType] = useState("HTTPS"); return <Modal title="Create health check" close={close} submit={e => { e.preventDefault(); save({ name, endpoint, check_type: checkType }); }}><p className="modal-intro">Monitor an endpoint and use its health status when routing traffic.</p><label>Health check name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Website endpoint" /></label><label>Endpoint<input required value={endpoint} onChange={e => setEndpoint(e.target.value)} placeholder="https://example.com/health" /></label><label>Check type<select value={checkType} onChange={e => setCheckType(e.target.value)}><option>HTTPS</option><option>HTTP</option><option>TCP</option></select></label></Modal>; }
function ResolverEndpointModal({ close, save }: { close: () => void; save: (data: { name: string; direction: string }) => Promise<void> }) { const [name, setName] = useState(""); const [direction, setDirection] = useState("Outbound"); return <Modal title="Create resolver endpoint" close={close} submit={e => { e.preventDefault(); save({ name, direction }); }}><p className="modal-intro">Create a DNS forwarding endpoint for your network.</p><label>Endpoint name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Default outbound resolver" /></label><label>Direction<select value={direction} onChange={e => setDirection(e.target.value)}><option>Outbound</option><option>Inbound</option></select></label></Modal>; }
function ProfileModal({ close, save }: { close: () => void; save: (data: { name: string; description: string }) => Promise<void> }) { const [name, setName] = useState(""); const [description, setDescription] = useState(""); return <Modal title="Create profile" close={close} submit={e => { e.preventDefault(); save({ name, description }); }}><p className="modal-intro">Create a reusable collection of DNS settings for an environment.</p><label>Profile name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Production profile" /></label><label>Description<textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Describe this profile" /></label></Modal>; }
